### PR TITLE
Run as Node debug

### PR DESCRIPTION
**Pull request by masterzion**
Add "Run as Node debug" (node --debug command line) in menu

### CODE REVIEW

**Comment by Acconut** [comment]
As far as I understand this, it's just a visual shortcut for adding `--debug` to the V8 flags settings, isn't it?

**Comment by masterzion** [comment]
yes.. I'm using this shortcut.

acttually i changed the paramter to "--debug-brk" in order to be compatible
with
https://github.com/TheBenji/brackets-node-debugger

I can commit this change too.


Best Regards

*Jairo Moreno*

2015-10-20 19:35 GMT-02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment]
Great, just one more question: What is the difference between the `--debug` option and using `node debug script.js`. I wasn't able to find appropriate information about this quickly.

**Comment by masterzion** [comment]
node debug is an interactive prompt and node --debug open a socket to use
another interface for debug.


Best Regards

*Jairo Moreno*

2015-10-21 18:17 GMT-02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment]
Thanks :)

**Comment by Acconut** [comment]
Version 1.4.2 should be released now.

**Pull request merged**
